# Generated by Django 3.1.4 on 2020-12-08 23:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('events', '0001_initial'), ('events', '0002_event_active'), ('events', '0003_auto_20201206_1624'), ('events', '0004_auto_20201206_2235'), ('events', '0005_auto_20201207_0032'), ('events', '0006_auto_20201207_1609'), ('events', '0007_auto_20201207_2042'), ('events', '0008_delete_streamingservice'), ('events', '0009_auto_20201208_2051'), ('events', '0010_auto_20201208_2117')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('stream_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('live_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('publisher_email', models.EmailField(blank=True, max_length=254)),
                ('publisher_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
