# Generated by Django 3.1.4 on 2020-12-09 16:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_rtmp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='publisher_name', unique_with=['publisher_name', 'starts_at']),
        ),
    ]
