# Generated by Django 3.1.4 on 2020-12-06 22:35

from django.db import migrations, models
import events.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201206_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rtmp_url',
            field=events.models.RTMPURLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventslot',
            name='live_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventslot',
            name='stream_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
