# Generated by Django 3.1.4 on 2020-12-10 00:55

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_slugify_existing_streams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_key',
        ),
        migrations.AddField(
            model_name='stream',
            name='key',
            field=models.CharField(default=events.models.get_uuid4, max_length=36, unique=True),
        ),
    ]
