# Generated by Django 3.1.4 on 2020-12-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20201206_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rtmp_url',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
