# Generated by Django 3.1.4 on 2020-12-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201210_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='preparation_time',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
