# Generated by Django 3.1.4 on 2020-12-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201207_1609'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventSlot',
            new_name='Stream',
        ),
    ]
