# Generated by Django 3.1.4 on 2020-12-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20201207_2042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamingService',
        ),
    ]
