# Generated by Django 3.1.4 on 2020-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_public_rtmp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
