# Generated by Django 3.1.4 on 2020-12-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20201208_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='live_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
