# Generated by Django 3.1.4 on 2020-12-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_stream_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stream',
            name='timezone',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
