# Generated by Django 3.1.4 on 2021-12-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20211205_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamnotification',
            name='kind',
            field=models.CharField(choices=[('CR', 'Created'), ('PR', 'Preparing'), ('UP', 'Updated'), ('RM', 'Removed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='streamnotification',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.stream'),
        ),
    ]
