# Generated by Django 3.1.13 on 2022-05-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_streamarchiveurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
