# Generated by Django 3.1.14 on 2024-02-05 15:23

from django.db import migrations
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_stream_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test_rtmp_url',
            field=events.models.RTMPURLField(blank=True, null=True),
        ),
    ]
