# Generated by Django 3.1.14 on 2024-02-05 20:58

from django.db import migrations
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_event_test_rtmp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public_rtmp_url',
            field=events.models.RTMPURLField(blank=True, default=events.models.get_default_public_rtmp_url, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rtmp_url',
            field=events.models.RTMPURLField(blank=True, default=events.models.get_default_rtmp_url, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='test_rtmp_url',
            field=events.models.RTMPURLField(blank=True, default=events.models.get_default_test_rtmp_url, null=True),
        ),
    ]
