# Generated by Django 3.1.14 on 2024-02-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20240205_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='description',
            new_name='title',
        ),
    ]
