# Generated by Django 3.1.14 on 2024-02-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_stream_rename_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
